version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - SECRET_KEY=macacobrasileiro
      - MONGODB_HOST=localhost
      - MONGODB_PORT=27017
      - MONGODB_DBNAME=test
      - MONGODB_USER=jaseggom
      - MONGODB_PASSWORD=Ja1977-1980
    ports:
      - "3000:3000"
  frontend:  
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - backend