version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - SECRET_KEY=macacobrasileiro
      - MONGODB_HOST=localhost
      - MONGODB_PORT=27017
      - MONGODB_DBNAME=test
      - MONGODB_USER=jaseggom
      - MONGODB_PASSWORD=Ja1977-1980
    ports:
      - "4000:3000"
  frontend:  
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - REACT_APP_URL=http://localhost:4000
    ports:
      - "4001:3000"
    depends_on:
      - backend
  sonarqube:
    image: "sonarqube"
    ports:
      - "9000:9000"
      - "9092:9092"
