openapi: 3.0.0
info:
  title: API
  description: 
  version: 1.0.0
components:
  definitions:
    Game:
      type: object
      properties:
        _id:
          type: string
        titulo:
          type: string
        descripcion:
          type: string
        unidades:
          type: integer
        categoria:
          type: array
          items:
            type: string
        precio:
          type: number
        imagen:
          type: string
        trailer:
          type: string
        pegi:
          type: integer
        desarrollador:
          type: string
        plataforma:
          type: string
        fechaLanzamiento:
          type: string
          format: date
    User:
        type: object
        properties:
          _id:
            type: string
          username:
            type: string
          name:
            type: string
          lastname:
            type: string
          country:
            type: string
          usernameImage:
            type: string
          email:
            type: string
          phoneNumber:
            type: number
          password:
            type: string
          rol:
            type: string
            enum:
              - Admin
              - User
  securitySchemes:
    jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /notes:
    schemes:
      - http
  /games:
    get:
      summary: Obtener todos los juegos
      tags: 
        - Games
      responses:
        200:
          description: Lista de juegos
    post:
      summary: Crear un juego
      tags: 
        - Games
      parameters:
        - name: rol
          in: header
          description: El rol del usuario
          required: true
          type: string
          default: Admin
      security:
        - rol: Admin
      requestBody:
        required: true
        content:
          application/json:
            example:
              titulo: "Ejemplo de título"
              descripcion: "Ejemplo de descripción"
              unidades: 10
              categoria: ["acción", "aventura"]
              precio: 19.99
              imagen: "https://ejemplo.com/imagen.jpg"
              trailer: "https://ejemplo.com/trailer.mp4"
              pegi: 18
              desarrollador: "Desarrollador"
              plataforma: "Steam"
              fechaLanzamiento: "2024-03-11"
      responses:
        201:
          description: Juego creado
  /games/titulo/{title}:
    get:
      summary: Obtener un juego por título
      tags: 
        - Games
      parameters:
        - name: title
          in: path
          required: true
          type: string
      responses:
        200:
          description: Detalles del juego
  /games/{id}:
    get:
      summary: Obtener un juego por ID
      tags: 
        - Games
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        200:
          description: Detalles del juego
    delete:
      summary: Eliminar un juego por ID
      tags: 
        - Games
      security:
        - rol: Admin
      parameters:
        - name: rol
          in: header
          description: El rol del usuario
          required: true
          type: string
          default: Admin
        - name: id
          in: path
          required: true
          type: string
      responses:
        200:
          description: Juego eliminado
  /games/admin/{id}:
    patch:
      summary: Actualizar un juego por ID
      tags:
        - Games
      security:
        - rol: Admin
      parameters:
        - name: rol
          in: header
          description: El rol del usuario
          required: true
          type: string
          default: Admin
        - name: id
          in: path
          description: ID del juego que se desea actualizar
          required: true
          type: string
        - name: game
          in: body
          description: Datos actualizados del juego
          required: true
          schema:
            type: object
            properties:
              unidades:
                type: integer
      responses:
        200:
          description: Juego actualizado
          schema:
            type: object
            properties:
              mensaje:
                type: string
                example: Juego actualizado correctamente
  /login:
    post:
      summary: Iniciar sesión
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: Token generado
        '401':
          description: Credenciales inválidas
  /users/me:
    get:
      summary: Obtener datos del usuario actual
      tags: 
        - Users
      security:
        - jwt: []
      responses:
        '200':
          description: Datos del usuario actual
  /users:
    get:
      summary: Obtener todos los usuarios
      tags: 
        - Users
      parameters:
        - name: rol
          in: header
          description: El rol del usuario
          required: true
          type: string
          default: Admin
      security:
        - rol: Admin
      responses:
        '200':
          description: Lista de usuarios
    post:
      summary: Crear un usuario
      tags: 
        - Users
      requestBody:
        required: true
        content:
          application/json:
            example:
              username: "usuario"
              password: "jajajaSouyUnAContraseñaSegura123"
              name: "Manolo"
              lastname: "Rodriguez"	
              email: "manolo@gmail.com"
              country: "Spain"
      responses:
        '201':
          description: Usuario creado
  /users/admin/{id}:
    patch:
      summary: Actualizar un usuario por ID
      tags: 
        - Users
      security:
        - rol: Admin
      parameters:
        - name: rol
          in: header
          description: El rol del usuario
          required: true
          type: string
          default: Admin
        - name: id
          in: path
          required: true
          type: string
        - name: user
          in: body
          required: true
          schema:
            type: object
            properties:
              lastname:
                type: string
      responses:
        '200':
          description: Usuario actualizado
        '404':
          description: Usuario no encontrado
  /users/{id}:
    delete:
      summary: Eliminar un usuario por ID
      tags: 
        - Users
      security:
        - rol: Admin
      parameters:
        - name: rol
          in: header
          description: El rol del usuario
          required: true
          type: string
          default: Admin
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: Usuario eliminado
        '404':
          description: Usuario no encontrado
  /carrito/{userId}:
    get:
      summary: Obtener productos del carrito
      tags:
        - Carrito
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      security:
        - jwt: []
      responses:
        '200':
          description: Productos del carrito
    post:
      summary: Añadir producto al carrito
      tags:
        - Carrito
      security:
        - jwt: []
      parameters:
        - name: rol
          in: header
          description: El rol del usuario
          required: true
          type: string
          default: Admin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                productId:
                  type: string
                cantidad:
                  type: integer
      responses:
        '201':
          description: Producto añadido al carrito
  /carrito/modificar:
    patch:
      summary: Modificar cantidad de producto en el carrito
      tags:
        - Carrito
      security:
        - jwt: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                carritoId:
                  type: string
                cantidad:
                  type: integer
      responses:
        '200':
          description: Cantidad de producto en el carrito modificada
  /carrito/{carritoId}:
    delete:
      summary: Eliminar producto del carrito
      tags:
        - Carrito
      security:
        - jwt: []
      parameters:
        - name: carritoId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Producto eliminado del carrito
  /factura/agregar:
    post:
      summary: Agregar una factura
      tags:
        - Facturas
      security:
        - rol: Admin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                productos:
                  type: array
                  items:
                    type: object
                    properties:
                      productoId:
                        type: string
                      unidades:
                        type: integer
                      precio:
                        type: number
      responses:
        '201':
          description: Factura agregada correctamente
        '400':
          description: Algo ha fallado
  /factura/{userId}:
    get:
      summary: Obtener todas las facturas de un usuario
      tags:
        - Facturas
      parameters:
        - name: userId
          in: path
          required: true
          schema:  
      responses:
        '200':
          description: Todas las facturas del usuario
  /factura/admin/{facturaId}:
      get:
        summary: Obtener una factura por ID
        tags:
          - Facturas
        parameters:
          - name: rol
            in: header
            description: El rol del usuario
            required: true
            type: string
            default: Admin
          - name: facturaId
            in: path
            required: true
            schema:
              type: string
        security:
          - rol: Admin
        responses:
          '200':
            description: Detalles de la factura
  /factura/{facturaId}:
    delete:
      summary: Eliminar una factura
      tags:
        - Facturas
      parameters:
        - name: rol
          in: header
          description: El rol del usuario
          required: true
          type: string
          default: Admin
        - name: facturaId
          in: path
          required: true
          schema:
            type: string
      security:
        - rol: Admin
      responses:
        '200':
          description: Factura eliminada correctamente

